### ISSUE TITLE
Getting Error on Spigot 1.8.6

### ISSUE THREAD

**Issue by Dennis000903** [ExtendedAlpha/SeparateWorldItems#23]
Could not pass event PlayerChangedWorldEvent to SeparateWorldItems v2.8.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerList.moveToWorld(PlayerList.java:623) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:475) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at com.earth2me.essentials.Teleport.now(Teleport.java:126) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Teleport.teleport(Teleport.java:194) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Teleport.warp(Teleport.java:263) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.commands.Commandwarp.warpUser(Commandwarp.java:130) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.commands.Commandwarp.run(Commandwarp.java:51) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:180) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:527) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:402) [Essentials-2.x-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:646) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_71]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_71]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:60) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
Caused by: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
        at org.json.JSONTokener.syntaxError(JSONTokener.java:433) ~[?:?]
        at org.json.JSONObject.<init>(JSONObject.java:197) ~[?:?]
        at org.json.JSONObject.<init>(JSONObject.java:324) ~[?:?]
        at com.ExtendedAlpha.SWI.SeparatorLib.Separator.getObjectFromStream(Separator.java:64) ~[?:?]
        at com.ExtendedAlpha.SWI.SeparatorLib.Separator.getObjectFromFile(Separator.java:60) ~[?:?]
        at com.ExtendedAlpha.SWI.Data.DataSeparator.getPlayerDataFromFile(DataSeparator.java:125) ~[?:?]
        at com.ExtendedAlpha.SWI.Listeners.ChangedWorldEventListener.onPlayerChangeWorld(ChangedWorldEventListener.java:70) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_71]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_71]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_71]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-6163031-01930e2]
        ... 29 more

I tried to delete the database because the error says something about an .json but that didnt work.

**Comment by TriptychPlaysMC** [comment]
Try using the latest dev build here: http://ci.md-5.net/job/SeparateWorldItems/

**Comment by Dennis000903** [comment]
Still an error :/

Could not pass event PlayerChangedWorldEvent to SeparateWorldItems v2.9.0-beta
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerList.moveToWorld(PlayerList.java:623) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:475) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at com.earth2me.essentials.Teleport.now(Teleport.java:126) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Teleport.teleport(Teleport.java:194) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Teleport.warp(Teleport.java:263) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.commands.Commandwarp.warpUser(Commandwarp.java:130) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.commands.Commandwarp.run(Commandwarp.java:51) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:180) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:527) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:402) [Essentials-2.x-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:646) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_71]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_71]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:60) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [craftbukkit.jar:git-Spigot-6163031-01930e2]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
Caused by: java.lang.UnsupportedClassVersionError: com/ExtendedAlpha/org/json/JSONException : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_71]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_71]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_71]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_71]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_71]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_71]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_71]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_71]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_71]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:195) ~[craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[craftbukkit.jar:git-Spigot-6163031-01930e2]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[craftbukkit.jar:git-Spigot-6163031-01930e2]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_71]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_71]
        at com.ExtendedAlpha.SWI.Listeners.ChangedWorldEventListener.onPlayerChangeWorld(ChangedWorldEventListener.java:56) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_71]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_71]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_71]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-6163031-01930e2]
        ... 29 more

**Comment by TriptychPlaysMC** [comment]
This is now fixed in latest dev build http://ci.md-5.net/job/SeparateWorldItems/34/

**Comment by Dennis000903** [comment]
Okay after updating it was still the same error, but then, after deleting the data it was fixed .. thanks
